#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
   echo "usage: run-sextractor IMAGENAME"
   exit
fi

sex -c sextractor.conf \
    -CATALOG_NAME cat.fits \
    -FILTER_NAME default.conv \
    -PARAMETERS_NAME sextractor.param \
    $1
